Tugas1PPW/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic.base import RedirectView

import update_status.urls as update_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^update-status/', include(update_status,namespace='update-status')),
	url(r'^$', RedirectView.as_view(url="update-status/", permanent="true"), name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_post

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-post', add_post, name='add-post'),
]

update_status/models.py
from django.db import models

class Post(models.Model):
	post = models.CharField(max_length=1600)
	created_date = models.DateTimeField(auto_now_add=True)

update_status/forms.py
from django import forms

class Post_Form(forms.Form):
	error_messages = {
		'required': 'Post Tidak Boleh Kosong',
	}
	attrs = {
		'class': 'text-design',
		'placeholder':"Apa yang anda pikirkan ....",
	}
	post = forms.CharField(error_messages=error_messages, label="", required=True, max_length=1600, widget=forms.Textarea(attrs=attrs))

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Post_Form
from .models import Post
# Create your views here.

response = {}
def index(request):
	html = 'update_status/updateStatus.html'
	response['post_form'] = Post_Form
	banyak = Post.objects.all().count()
	post = Post.objects.order_by('-created_date')
	response['post'] = post
	return render(request, html, response)

def add_post(request):
	form = Post_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['post'] = request.POST['post']
		post = Post(post=response['post'])
		post.save()
	return HttpResponseRedirect('/update-status/')

update_status/templates/update_status/tablePost.html
{% extends "update_status/updateStatus" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <!--  Populate semua isi pesan dari model -->
    <table>
        <thead>
            <th>Post: </th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in post %}
             <tr>
                <td> {{i.post}} </td>
                <td> {{i.created_date.time}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endblock %}

update_status/templates/update_status/updateStatus.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
    <title>
        Update Status
    </title>
</head>
<body class="body">
	<div class="wraper">
		<div class="form-panel-head">
			<h1 class="data">Update Status</h1>
			<form id="form" method="POST" action="{% url 'update-status:add-post' %}">
					{% csrf_token %}
					{{ post_form }}
					<br>
				<button class="button-design" type="submit">Post</button>
			</form>
		</div>
		<div class="container">
			<div class="flex">
			  {% for i in post %}
				<div class="flex-item">
					<div class="posts">
						<!--div class="post-profile">
						</div-->
						<div>
							<p style="white-space:pre">{{i.post}}</p>
						</div>
						<div class="post-date">{{i.created_date|date:"d M Y G:i:s"}}</div>
					</div>
				</div>
			  {% endfor %}
			</div>
		</div>
	</div>
</body>
</html>